### ISSUE TITLE
librespot Music stops abruptly when playing long playlists

### ISSUE THREAD

**Issue by COMPsmith** [sweisgerber/docker-snapcast#12]
What librespot version is included in this docker image? Im having issues of music stopping on long playlist. I need 24 Spotify streaming.

Related issues and version recommendation 
https://github.com/librespot-org/librespot/issues/1238

v0.5 should be out soon
https://github.com/librespot-org/librespot/issues/1279

**Comment by sweisgerber** [comment]
I'm utilizing librespot from alpine: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/librespot in version `0.4.2-r4`.
I can't provide specialized versions from unmerged PRs, sorry.

**Comment by COMPsmith** [comment]
Understood. Will have to wait until v0.5 is released and picked up by alpine.
