### ISSUE TITLE
Message to enable SnapClient keeps repeating in the log

### ISSUE THREAD

**Issue by sam-19** [sweisgerber/docker-snapcast#4]
Thank you for this docker image! I successfully configured and started it, using `START_SNAPCLIENT=false`. However, during the several minutes that I ran it, the message `Not starting snapclient. Set 'START_SNAPCLIENT=true' to start it.` kept appearing in the log every few seconds. I suspected this would keep repeating indefinitely and had to stop the container.

I believe the following line is responsible for the message.

https://github.com/sweisgerber/docker-snapcast/blob/924f8b0f90d2a8380cdb6bdeffbd10507f72eaf1/root/etc/s6-overlay/s6-rc.d/svc-snapclient/run#L17

Is it possible to configure the container to only show this message once if SnapClient is disabled?

**Comment by sweisgerber** [comment]
Thanks, good point. I fixed it in https://github.com/sweisgerber/docker-snapcast/pull/5 :)
